Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -14,35 +14,36 @@ jobs:
     runs-on: ubuntu-latest
     environment: production
 
-    # Use the Bash shell regardless of the GitHub Actions runner's OS
     defaults:
       run:
         shell: bash
 
     steps:
-      # Checkout the repository to the GitHub Actions runner
       - name: Checkout
         uses: actions/checkout@v4
 
-      # Install the latest version of Terraform CLI and configure it with the Terraform Cloud user API token
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v1
         with:
           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-      # Initialize the Terraform working directory for the 'prod' environment
-      - name: Terraform Init
-        run: terraform init -backend-config="path=POC-terraform/env/prod/terraform.tfstate"
+      # Ensure that the directory contains Terraform files before proceeding
+      - name: Check Terraform Files
+        run: |
+          if [ ! -f "POC-terraform/env/prod/main.tf" ]; then
+            echo "Error: main.tf not found in POC-terraform/env/prod"
+            exit 1
+          fi
 
-      # Check that all Terraform configuration files adhere to a canonical format
+      - name: Terraform Init
+        run: terraform init -backend-config="path=POC-terraform/env/prod"
+
       - name: Terraform Format
         run: terraform fmt -check POC-terraform/env/prod
 
-      # Generate an execution plan for Terraform
       - name: Terraform Plan
         run: terraform plan -input=false -var-file="POC-terraform/env/prod/prod.tfvars"
 
-      # Apply the changes to the infrastructure on push to "main"
       - name: Terraform Apply
         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
         run: terraform apply -auto-approve -input=false -var-file="POC-terraform/env/prod/prod.tfvars"
